---
Name: ecommerce-advance-retail-connector-routes
After: '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    admin-test/advanceretailtest//$Action/$ID/$OtherID: Sunnysideup\EcommerceAdvanceRetailConnector\Control\ARTestController
